
behav_columns_to_drop = [
    'bin_end_time',
    'bin_start_time',
    'crossing_boundary',
    'cum_distance_when_target_last_seen',
    'current_target_caught_time',
    'dt',
    'gaze_mky_view_angle',
    'gaze_mky_view_x',
    'gaze_mky_view_y',
    'gaze_world_x',
    'gaze_world_y',
    'last_target_caught_time',
    'monkey_angle_target_last_seen',
    'monkey_dw_smr',
    'monkey_speed_smr',
    'monkey_x_smr',
    'monkey_y_smr',
    'target_has_disappeared_for_last_time_dummy',
    'target_visible_dummy',
    'trial',
    'turning_right',
    'valid_view_point'
    ]