function [] = TempAlignNeuralData()
AlignNeuralData('/Users/dusiyi/Documents/Multifirefly-Project/all_monkey_data/neural_data/monkey_Bruno/data_0323/m51s005.plx', ...
    '/Users/dusiyi/Documents/Multifirefly-Project/all_monkey_data/metadata/monkey_Bruno/data_0323/neural_time_offset_long.txt', ...
    1000)
end